### ISSUE TITLE
Немного прыгает календарь при переключении месяца

### ISSUE THREAD

**Issue by WebPolyglot** [IrinaOsotova/CALORY#10]
Ячейки дней недели и сами даты немного разъезжаются при переключении месяца
1. Выбрал Апрель 1991 г
![image](https://user-images.githubusercontent.com/110096481/205627534-55472df6-9a7d-4b2a-96b4-b193555b1b43.png)
2. Переключил на Май 1991 г.
![image](https://user-images.githubusercontent.com/110096481/205627605-d4af99c9-65fe-4dc5-b879-ed47a045da2b.png)
Результат. Немного поехали даты.
Ожидалось: Что не будет никаких скачков между переключаемыми месяцами

**Comment by AnroMel** [comment]
Спасибо за оставленную ошибку.
Команда разработчиков использовали системный календарь, в котором обозначения недель ( П В С Ч П С В ) подстраиваются под ширину колонок с цифрами ( разные цифры занимают разную ширину ) 
Если многим пользователям  данный элемент будет отвлекать или мешать, мы это обязательно исправим
