### ISSUE TITLE
курсор

### ISSUE THREAD

**Issue by WebPolyglot** [IrinaOsotova/CALORY#11]
По всему sidebar cursor: pointer, хотелось бы, чтобы он был только на ссылках, иначе уж очень хочется кликнуть. В других местах где при клике ничего не происходит соответственно - cursor:default.  Так же уж очень хочется кликнуть на CALORY. Можно сделать при клике на CALORY переход на главную
![image](https://user-images.githubusercontent.com/110096481/205629980-26c3745b-b4bc-497c-9145-fb5169a068dd.png)

**Comment by IrinaOsotova** [comment]
Спасибо за оставленную ошибку. Исправили.
