### ISSUE TITLE
Возможность поменять данные профиля, не нажимая кнопку "Изменить параметры"

### ISSUE THREAD

**Issue by wmaksimova** [IrinaOsotova/CALORY#12]
1. Открываю приложение, захожу в аккаунт
2. Захожу во вкладку "Профиль", хочу изменить данные
3. Нажимаю кнопку " Изменить параметры", ухожу на другую вкладку, не нажав кнопку "Сохранить"
![KhI72JNWEgA](https://user-images.githubusercontent.com/87775914/205670707-4abe70ae-ba94-4c37-b6b9-f4cff0ca5dfd.jpg)
4. Возвращаюсь на вкладку "Профиль", вижу, что данные можно поменять без нажатия на кнопку " Изменить параметры "
![HT6umn5dEeg](https://user-images.githubusercontent.com/87775914/205671181-ff8d3d7a-ca40-4923-bcf5-3f9df3b553cd.jpg)
5. Ожидалось: запрет на изменения данных без нажатия соответствующей кнопки

**Comment by AnroMel** [comment]
Спасибо что выбрали наш продукт.
Благодарим за оставленную ошибку, команда разработчиков исправили её
