### ISSUE TITLE
Сохранение новых данных

### ISSUE THREAD

**Issue by PolinaTaba** [IrinaOsotova/CALORY#13]
![image](https://user-images.githubusercontent.com/113423099/205703982-5e384808-5359-4c43-832b-8b82f0772495.png)

При сохранении новых данных непонятно, сохранилась ли обновленная информация или нет. Хотелось бы какое-нибудь сообщение об успешном изменении или же наоборот...

**Comment by AnroMel** [comment]
Спасибо что выбрали наш продукт.
Благодарим за оставленную ошибку, команда разработчиков исправили её
