### ISSUE TITLE
Отчеты дней.

### ISSUE THREAD

**Issue by PolinaTaba** [IrinaOsotova/CALORY#14]
в отчетах нельзя просматривать соотношение белков углеводов и жиров за предыдущие дни, а только за сегодняшний

**Comment by AnroMel** [comment]
Спасибо что выбрали наш продукт.
Благодарим за оставленную ошибку, командой разработчиков было задумано сделать соотношение белков углеводов и жиров в виде диаграммы только за текущий день. Если многим пользователям будет нужно просматривать диаграмму за предыдущие дни, мы обязательно добавим такую функцию !
