### ISSUE TITLE
Большой диапазон выбора дат

### ISSUE THREAD

**Issue by xdashie** [IrinaOsotova/CALORY#15]
1. Захожу в приложение
2. Хочу выбрать дату
3. Нет нижней границы при выборе
![image](https://user-images.githubusercontent.com/113391483/205728173-0d1dc270-4208-47b0-8488-3aed92a7c48c.png)
4. Ожидалась разумная нижняя граница

**Comment by vallerili** [comment]
Спасибо за сообщение об ошибке! Все исправлено, выбор дат теперь ограничен
