### ISSUE TITLE
Нет валидации файла products.txt

### ISSUE THREAD

**Issue by sealwestrow** [IrinaOsotova/CALORY#2]
1. Изменил данные в файле products.txt
2. Запустил приложение
3. При входе приложение вылетает
Ожидалось: программа проверяет файл на соответствие формату  JSON, и в случае несоответствия уведомляет пользователя об этом.

**Comment by AnroMel** [comment]
Спасибо за оставленную ошибку.
products.txt файл, который не будет передан пользователям и не должен у них находится в доступе, это ресурс проекта. И изменять его могут только разработчики проекта.
