### ISSUE TITLE
Некорректное выделение кнопки поиска

### ISSUE THREAD

**Issue by 943ml1n** [IrinaOsotova/CALORY#3]
1. Запустил приложение
2. Авторизовался
3.  На вкладке "Дневник", в строке поиска иконка поиска выехала за поле, а также она отображается поверх кнопки открытия списка
![image](https://user-images.githubusercontent.com/116759793/205510633-c418c223-b8fc-4d9b-8f2d-28bcca86c8df.png)
Ожидалось: элементы будут отображаться ровно, не "наезжая" друг на друга

**Comment by IrinaOsotova** [comment]
Благодарим за оставленную ошибку, команда разработчиков исправили её
