### ISSUE TITLE
Нет возможности удалить несколько продуктов в дневнике

### ISSUE THREAD

**Issue by sealwestrow** [IrinaOsotova/CALORY#4]
1. Открыл приложение
2. Зашел на вкладку "Дневник"
3. Добавил несколько продуктов в раздел "Завтрак"
4. Можно выбрать только один продукт для удаления.
![image](https://user-images.githubusercontent.com/99202907/205511624-a2fc3846-3fb9-4c8d-9dd6-cde0cfd73312.png)
Ожидалось: Возможность выбора нескольких продуктов, либо отдельная кнопка "Удалить все продукты"

**Comment by AnroMel** [comment]
Спасибо за оставленную ошибку.
В нашем приложении можно удалять продукты по одному, потому что мы считаем, что больше пользователям не нужно. В среднем за прием пищи человек съедает не более пяти наименований продуктов
Также мы проанализировали приложения, который имеют похожий функционал и заметили что ни в одном не реализовано удаление двух и более продуктов питания.
