### ISSUE TITLE
Отсутствует возможность открытия на весь экран

### ISSUE THREAD

**Issue by 943ml1n** [IrinaOsotova/CALORY#5]
1. Зашёл в приложение
2. Нет возможности развернуть окно на весь экран
![image](https://user-images.githubusercontent.com/116759793/205511700-65030c95-c790-4ee5-9965-d102f629fa76.png)
Ожидалось: функционирующая кнопка на весь экран "На весь экран"

**Comment by AnroMel** [comment]
Спасибо за оставленную ошибку.
Разработчиками было задумано создать приложение, которое будет иметь статический размер. Но мы в будущем задумаемся о создании адаптируемого приложения под полный экран, если пользователям будет удобнее.
