### ISSUE TITLE
Не отображается конечный вес при выборе/изменении цели

### ISSUE THREAD

**Issue by sealwestrow** [IrinaOsotova/CALORY#6]
1. Открываю приложение
2. Открываю вкладку "Профиль"
3. Изменяю цель
4. Не отображается "целевой" вес
![image](https://user-images.githubusercontent.com/99202907/205511988-33bb930b-9ebf-4054-8551-76f02d75d27b.png)

Ожидалось: при выборе/изменении цели отображается вес, получаемый при достижении цели

**Comment by AnroMel** [comment]
Спасибо за оставленную ошибку.
Команда разработчиков не совсем понимает, что подразумевается под "отображается вес, получаемый при достижении цели". Наше приложение играет роль подробного учета всего того, что вы съели в течение дня, а также мы считаем по вашим особенностям и предпочтениям РСК. Оно изменяется от вашей цели. Прослеживать какого веса вы добьетесь используя наше приложение нет в нашем функционале. На это влияет очень много факторов:
1. Сколько вы пьете воды
2. Строение тела и заболевания
3. Сколько вы проходите в день шагов и ваши физические активности в полном объёме
4. Сон, стресс, депрессия и многое другое.
