### ISSUE TITLE
Отсутствует возможность восстановления пароля

### ISSUE THREAD

**Issue by 943ml1n** [IrinaOsotova/CALORY#7]
1. Зашёл в программу
2. Пробую ввести данные от аккаунта
3.  Понимаю, что забыл пароль
Следствие: не могу войти в аккаунт
![image](https://user-images.githubusercontent.com/116759793/205512117-ad73f1b1-8324-4cc8-83c1-03d175da01e8.png)
Ожидалось: опция восстановления пароля

**Comment by AnroMel** [comment]
Спасибо за оставленную ошибку.
Команда разработчиков на данный момент не имеет возможности сделать восстановление пароля, если пользователь его забыл. Для это нам нужно будет запрашивать при регистрации email, номер телефона или ссылку на социальные сети. Но обязательно в будущем, мы задумаемся об этом.
