### ISSUE TITLE
Грамматическая ошибка в описании приложения

### ISSUE THREAD

**Issue by wmaksimova** [IrinaOsotova/CALORY#8]
1. Открываю приложение
2. Читаю описание
3. Грамматическая ошибка в слове "неотъемлемый"
![image](https://user-images.githubusercontent.com/87775914/205514649-855bae58-ab78-4070-b08a-faead0ec6bf6.png)
4. Ожидалось: корректное описание приложения

**Comment by IrinaOsotova** [comment]
Благодарим за оставленную ошибку, команда разработчиков исправили её
