### ISSUE TITLE
Отсутствует подсчёт калорий за день 

### ISSUE THREAD

**Issue by sergeilubimkov** [IrinaOsotova/CALORY#9]
Не очень удобно каждый раз переключаться на раздел "Отчет", чтобы посмотреть кол-во калорий уже мной съеденных. Было бы удобнее, если бы можно было это посмотреть на главной странице.

**Comment by AnroMel** [comment]
Спасибо за оставленную ошибку.
Разработчиками было запланировано, чтобы можно было посмотреть количество съеденных калорий и соотношение белков, жиров и углеводов на странице "отчеты". Если переносить первое, то нужно и второе.
Для облегчения интерфейса и избежания гиперинформированности на страницах, мы сделали так.
Если большинству пользователей будет удобнее смотреть съеденные калории на главной странице (Дневник), то мы сделаем это.
